---
- hosts: raspi
  become: yes
  roles:
    - pre
    - post
  vars:
    mechatrax_release: stretch
    mechatrax_archive_url: http://mechatrax.github.io/raspbian/
    mechatrax_archive_keyring_deb: mechatrax-archive-keyring_2016.12.19.1_all.deb
    mechatrax_archive_keyring_sha256sum: 2a7039dc91e0c6f768ccc3fc1b1cdfd9af04cf9eb45b77a065e457cec8570e83
